---
# TODO: transfer files for Docker
- name: Log into DockerHub
  docker_login:
    username: sinkers
    password: '{{ dockerhub_password }}'
    email: sinclair.j@gmail.com
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module
- name: Tear down existing services
  community.docker.docker_compose:
    project_src: flask
    state: absent
- name: Create and start services
  community.docker.docker_compose:
    project_src: flask
  register: output
- ansible.builtin.debug:
    var: output
- name: Run `docker-compose up` again
  community.docker.docker_compose:
    project_src: flask
    build: no
  register: output
- ansible.builtin.debug:
    var: output
- ansible.builtin.assert:
    that: "not output.changed "
- name: Stop all services
  community.docker.docker_compose:
    project_src: flask
    build: no
    stopped: yes
  register: output
- ansible.builtin.debug:
    var: output
- ansible.builtin.assert:
    that:
      - "not flask.flask_flask_1.state.running"

- name: Restart services
  community.docker.docker_compose:
    project_src: flask
    build: no
    restarted: yes
  register: output
- ansible.builtin.debug:
    var: output
- ansible.builtin.assert:
    that:
      - "flask.flask_flask_1.state.running"