---
# run flask in docker container using docker-compose
- name: Create flask directory
  ansible.builtin.file:
    path: ~/flask/
    state: directory
- name: Copy flask files to VM
  ansible.builtin.copy:
    src: ../../docker-compose.yml
    dest: flask/docker-compose.yml
- name: Log into DockerHub
  docker_login:
    username: sinkers
    password: '{{ dockerhub_password }}'
    email: sinclair.j@gmail.com
# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_compose_module.html#ansible-collections-community-docker-docker-compose-module
- name: Tear down existing services
  community.docker.docker_compose:
    project_src: flask
    state: absent
- name: Create and start services
  community.docker.docker_compose:
    project_src: flask
  register: output
- ansible.builtin.debug:
    var: output
- name: Run `docker-compose up` 
  community.docker.docker_compose:
    project_src: flask
    build: no
  register: output
- ansible.builtin.debug:
    var: output
- ansible.builtin.assert:
    that: "not output.changed "
